# Generated by Django 3.0.6 on 2020-05-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200526_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='item',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='app/static/img/default.jpg', upload_to='app/static/img/profile_pictures/1301936494/'),
        ),
        migrations.DeleteModel(
            name='Encomenda',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
