# Generated by Django 3.0.2 on 2020-05-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200527_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
