# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains

class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_untitled(self):
        # Test name: Untitled
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("http://localhost:8000/")
        # 2 | setWindowSize | 1552x849 |
        self.driver.set_window_size(1552, 849)
        # 3 | click | id=navbarDefault |
        self.driver.find_element(By.ID, "navbarDefault").click()
        # 4 | click | id=navbarDefault |
        self.driver.find_element(By.ID, "navbarDefault").click()
        # 5 | click | id=navbarDefault |
        self.driver.find_element(By.ID, "navbarDefault").click()
        # 6 | click | css=.navbar |
        self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
        # 7 | click | css=.navbar > .container |
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > .container").click()
        # 8 | click | css=.navbar |
        self.driver.find_element(By.CSS_SELECTOR, ".navbar").click()
        # 9 | click | linkText=Ver mais |
        self.driver.find_element(By.LINK_TEXT, "Ver mais").click()
        # 10 | click | css=.col-lg-12:nth-child(2) th:nth-child(1) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(1)").click()
        # 11 | click | css=.col-lg-12:nth-child(2) th:nth-child(1) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(1)").click()
        # 12 | doubleClick | css=.col-lg-12:nth-child(2) th:nth-child(1) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 13 | click | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)").click()
        # 14 | click | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)").click()
        # 15 | doubleClick | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 16 | click | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)").click()
        # 17 | click | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)").click()
        # 18 | doubleClick | css=.col-lg-12:nth-child(2) th:nth-child(2) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 19 | click | css=.col-lg-12:nth-child(2) th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(3)").click()
        # 20 | click | css=.col-lg-12:nth-child(2) th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(3)").click()
        # 21 | doubleClick | css=.col-lg-12:nth-child(2) th:nth-child(3) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(2) th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 22 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(1) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(1)").click()
        # 23 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(1) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(1)").click()
        # 24 | doubleClick | css=.col-lg-12:nth-child(3) > .table th:nth-child(1) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 25 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(2)").click()
        # 26 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(2) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(2)").click()
        # 27 | doubleClick | css=.col-lg-12:nth-child(3) > .table th:nth-child(2) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(2)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 28 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)").click()
        # 29 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)").click()
        # 30 | doubleClick | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 31 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)").click()
        # 32 | click | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)").click()
        # 33 | doubleClick | css=.col-lg-12:nth-child(3) > .table th:nth-child(3) |
        element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(3) > .table th:nth-child(3)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 34 | click | css=th:nth-child(4) |
        self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(4)").click()
        # 35 | click | css=th:nth-child(4) |
        self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(4)").click()
        # 36 | doubleClick | css=th:nth-child(4) |
        element = self.driver.find_element(By.CSS_SELECTOR, "th:nth-child(4)")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        # 37 | click | css=.card-body |
        self.driver.find_element(By.CSS_SELECTOR, ".card-body").click()
        # 38 | click | css=.fa |
        self.driver.find_element(By.CSS_SELECTOR, ".fa").click()

